# Workaround. Prevent appearing 0;10;1c when tmux start
set -sg escape-time 1

# Workaround. Prevent pixel count characters appearing when ssh-ing in
set -as terminal-features ',*:-sixel'

# Enable mouse
set -g mouse on

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-space send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Start windows andpanes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Rebind horizontal and vertical splits
unbind '"'
unbind %

# Open panes in current directory
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Installing plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Catppuccin configuration
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_status_background "default"

# Catppuccin status bar
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session user host"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

# Transparent status line
set -g status-bg default
set-option -g status-style bg=default

run '~/.tmux/plugins/tpm/tpm'
