#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:peach'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:sapphire>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

      [blocks.segments.properties]
        branch_icon = ''
        commit_icon = '@'
        fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}p:red{{end}}',
      '{{if eq .Code 0}}p:pink{{end}}',
    ]
    background = 'plain'
    template = '❯'

[transient_prompt]
  foreground = 'p:pink'
  background = 'transparent'
  template = '❯ '

[palette]
  rosewater = '#f5e0dc'
  flamingo = '#f2cdcd'
  pink = '#f5c2e7'
  mauve = '#cda6f7'
  red = '#f38ba8'
  maroon = '#eba0ac'
  peach = '#fab387'
  yellow = '#f9e2af'
  green = '#a6e3a1'
  teal = '#94e2d5'
  sky = '#89dceb'
  sapphire = '#74c7ec'
  blue = '#89b4fa'
  lavender = '#b4befe'
  text = '#cdd6f4'
